package struct_info

import (
	"errors"
	"quick-crud/helpers"
	"reflect"
	"slices"
	"strconv"
	"strings"
	"sync"
)

var tagName = "tbl"

const (
	keyPK      = "pk"      // Primary key
	keyRO      = "ro"      // selecting only (read only)
	keyAuto    = "auto"    // Autogenerated (no inserting)
	keyEmbed   = "embed"   // struct embedding
	keyOmit    = "omit"    // Full field ignore
	keyColName = "col="    // Column name
	keyInsert  = "ins"     // force field inserting
	keyUpdate  = "upd"     // force field updating
	keyHide    = "rskip"   // skip field on selecting
	keyPrefix  = "prefix=" // Subcolumns name prefix
	keyRef     = "ref="    // FK reference
	keySort    = "sort="   // Sort <position>[:desc]
	keyDesc    = "desc"    // Descending sort direction
)
const keySeparator = ";"
const inKeySeparator = ","
const inKVSeparator = ":"

type FieldTagFlags struct {
	IsPK        bool // keyPK
	ReadOnly    bool // keyRO
	AutoGen     bool // keyAuto
	Embed       bool
	ForceUpdate bool
	ForceInsert bool
	SkipReading bool
	ColName     string // keyColName
	Prefix      string // keyPrefix
	Ref         string
	Sort        string
}

func (f *FieldTagFlags) Merge(parent FieldTagFlags) {
	f.IsPK = f.IsPK || parent.IsPK
	f.ReadOnly = f.ReadOnly || parent.ReadOnly
	f.AutoGen = f.AutoGen || parent.AutoGen
	f.ForceUpdate = f.ForceUpdate || parent.ForceUpdate
	f.ForceInsert = f.ForceInsert || parent.ForceInsert
	f.SkipReading = f.SkipReading || parent.SkipReading
	// no Embed merging
	// no ColName merging
	f.Prefix = parent.Prefix + f.Prefix
	// no Ref merging
	if f.Sort == "" {
		f.Sort = parent.Sort
	}
}

func isKey(key, val string) bool {
	l := len(key)
	return len(val) >= l && val[:l] == key
}

func parseFieldTag(tag string) (result FieldTagFlags, ok bool) {
	keys := strings.Split(tag, keySeparator)
	for _, key := range keys {
		switch {
		case key == keyPK:
			result.IsPK = true
		case key == keyRO:
			result.ReadOnly = true
		case key == keyAuto:
			result.AutoGen = true
		case key == keyEmbed:
			result.Embed = true
		case isKey(keyOmit, key):
			return result, false // return false !!!
		case key == keyInsert:
			result.ForceInsert = true
		case key == keyUpdate:
			result.ForceUpdate = true
		case key == keyHide:
			result.SkipReading = true
		case isKey(keyColName, key):
			result.ColName = key[len(keyColName):]
		case isKey(keyPrefix, key):
			result.Prefix = key[len(keyPrefix):]
		case isKey(keyRef, key):
			result.Ref = key[len(keyRef):]
		case isKey(keySort, key):
			result.Sort = key[len(keySort):]
		}
	}
	return result, true
}

var collectTableFieldsCache sync.Map

func CollectTableFields(t reflect.Type) (TableFields, error) {
	if t.Kind() != reflect.Struct {
		return nil, errors.New("expects a struct's type argument")
	}

	if v, ok := collectTableFieldsCache.Load(t); ok {
		return v.(TableFields), nil //nolint:errcheck
	}

	result := make(TableFields, 0, t.NumField())
	for idx := range t.NumField() {
		newFields := collectFieldInfo(t.Field(idx), FieldTagFlags{})
		result = append(result, newFields...)
	}

	collectTableFieldsCache.Store(t, result)

	return result, nil
}

func collectFieldInfo(fld reflect.StructField, parentFlags FieldTagFlags) []TableField {
	if !fld.IsExported() {
		return nil
	}

	flags, processable := parseFieldTag(fld.Tag.Get(tagName))
	if !processable {
		return nil
	}
	flags.Merge(parentFlags)

	if fld.Type.Kind() == reflect.Struct && (fld.Anonymous || flags.Embed || flags.Prefix != "") {
		result := make([]TableField, 0, fld.Type.NumField())
		// Поле-структура требует "распаковки" на отдельные поля
		subField := fld.Type

		for i := range subField.NumField() {
			subResult := collectFieldInfo(subField.Field(i), flags)
			for idx := range subResult {
				subResult[idx].Index = append(fld.Index, subResult[idx].Index...)
				subResult[idx].Path = slices.Insert(subResult[idx].Path, 0, fld.Name)
			}
			result = append(result, subResult...)
		}
		return result
	}

	tblFld := TableField{
		Index:     fld.Index,
		Path:      []string{fld.Name},
		IsPK:      flags.IsPK,
		CanSelect: flags.canSelect(),
		CanInsert: flags.canInsert(),
		CanUpdate: flags.canUpdate(),
		SQLName:   flags.ColName,
	}
	if tblFld.SQLName == "" {
		tblFld.SQLName = helpers.ToSnakeCase(fld.Name)
	}
	tblFld.SQLName = flags.Prefix + tblFld.SQLName

	sort := strings.SplitN(flags.Sort, inKVSeparator, 2)
	if len(sort) > 0 {
		tblFld.SortPos, _ = strconv.Atoi(sort[0])
	}
	if tblFld.SortPos > 1 {
		tblFld.SortBackward = strings.ToLower(sort[1]) == keyDesc
	}

	ref := strings.SplitN(flags.Ref, inKVSeparator, 2)
	if len(ref) == 2 {
		tblFld.RefTable, tblFld.RefField = ref[0], ref[1]
	}

	return []TableField{tblFld}
}

func (f *FieldTagFlags) canInsert() bool {
	return f.ForceInsert || !f.ReadOnly && !f.AutoGen
}

func (f *FieldTagFlags) canUpdate() bool {
	return f.ForceUpdate || !f.ReadOnly && !f.IsPK
}

func (f *FieldTagFlags) canSelect() bool {
	return !f.SkipReading
}
