package struct_info

import (
	"errors"
	"reflect"
	"slices"
	"strconv"
	"strings"
	"sync"

	"github.com/mirrorru/cruds/helpers"
)

var TagName = "tbl"

const (
	KeyPK      = "pk"      // Primary key
	KeyRO      = "ro"      // selecting only (read only)
	KeyAuto    = "auto"    // Autogenerated (no inserting)
	KeyEmbed   = "embed"   // struct embedding
	KeyOmit    = "omit"    // Full field ignore
	KeyColName = "col="    // Column name
	KeyInsert  = "ins"     // force field inserting
	KeyUpdate  = "upd"     // force field updating
	KeyHide    = "rskip"   // skip field on selecting
	KeyPrefix  = "prefix=" // Subcolumns name prefix
	KeyRef     = "ref="    // FK reference
	KeySort    = "sort="   // Sort <position>[:desc]
	KeyDesc    = "desc"    // Descending sort direction

	KeysSeparator  = ";"
	InKeySeparator = ","
	InKVSeparator  = ":"
)

type FieldTagFlags struct {
	IsPK        bool // keyPK
	ReadOnly    bool // keyRO
	AutoGen     bool // keyAuto
	Embed       bool
	ForceUpdate bool
	ForceInsert bool
	SkipReading bool
	ColName     string // keyColName
	Prefix      string // keyPrefix
	Ref         string
	Sort        string
}

func (f *FieldTagFlags) Merge(parent FieldTagFlags) {
	f.IsPK = f.IsPK || parent.IsPK
	f.ReadOnly = f.ReadOnly || parent.ReadOnly
	f.AutoGen = f.AutoGen || parent.AutoGen
	f.ForceUpdate = f.ForceUpdate || parent.ForceUpdate
	f.ForceInsert = f.ForceInsert || parent.ForceInsert
	f.SkipReading = f.SkipReading || parent.SkipReading
	// no Embed merging
	// no ColName merging
	f.Prefix = parent.Prefix + f.Prefix
	// no Ref merging
	if f.Sort == "" {
		f.Sort = parent.Sort
	}
}

func IsKey(key, val string) bool {
	l := len(key)
	return len(val) >= l && val[:l] == key
}

func parseFieldTag(tag string) (result FieldTagFlags, ok bool) {
	keys := strings.Split(tag, KeysSeparator)
	for _, key := range keys {
		switch {
		case key == KeyPK:
			result.IsPK = true
		case key == KeyRO:
			result.ReadOnly = true
		case key == KeyAuto:
			result.AutoGen = true
		case key == KeyEmbed:
			result.Embed = true
		case IsKey(KeyOmit, key):
			return result, false // return false !!!
		case key == KeyInsert:
			result.ForceInsert = true
		case key == KeyUpdate:
			result.ForceUpdate = true
		case key == KeyHide:
			result.SkipReading = true
		case IsKey(KeyColName, key):
			result.ColName = key[len(KeyColName):]
		case IsKey(KeyPrefix, key):
			result.Prefix = key[len(KeyPrefix):]
		case IsKey(KeyRef, key):
			result.Ref = key[len(KeyRef):]
		case IsKey(KeySort, key):
			result.Sort = key[len(KeySort):]
		}
	}
	return result, true
}

var collectTableFieldsCache sync.Map

func CollectTableFields(t reflect.Type) (TableFields, error) {
	if t.Kind() != reflect.Struct {
		return nil, errors.New("expects a struct's type argument")
	}

	if v, ok := collectTableFieldsCache.Load(t); ok {
		return v.(TableFields), nil //nolint:errcheck
	}

	result := make(TableFields, 0, t.NumField())
	for idx := range t.NumField() {
		newFields, err := collectFieldInfo(t.Field(idx), FieldTagFlags{})
		if err != nil {
			return nil, err
		}
		result = append(result, newFields...)
	}

	collectTableFieldsCache.Store(t, result)

	return result, nil
}

func collectFieldInfo(fld reflect.StructField, parentFlags FieldTagFlags) (_ []TableField, err error) {
	if !fld.IsExported() {
		return nil, nil
	}

	flags, processable := parseFieldTag(fld.Tag.Get(TagName))
	if !processable {
		return nil, nil
	}
	flags.Merge(parentFlags)

	if fld.Type.Kind() == reflect.Struct && (fld.Anonymous || flags.Embed || flags.Prefix != "") {
		result := make([]TableField, 0, fld.Type.NumField())
		// Поле-структура требует "распаковки" на отдельные поля
		subField := fld.Type

		for i := range subField.NumField() {
			subResult, err := collectFieldInfo(subField.Field(i), flags)
			if err != nil {
				return nil, err
			}
			for idx := range subResult {
				subResult[idx].Index = append(fld.Index, subResult[idx].Index...)
				subResult[idx].Path = slices.Insert(subResult[idx].Path, 0, fld.Name)
			}
			result = append(result, subResult...)
		}
		return result, nil
	}

	tblFld := TableField{
		Index:     fld.Index,
		Path:      []string{fld.Name},
		IsPK:      flags.IsPK,
		CanSelect: flags.canSelect(),
		CanInsert: flags.canInsert(),
		CanUpdate: flags.canUpdate(),
		SQLName:   flags.ColName,
	}
	if tblFld.SQLName == "" {
		tblFld.SQLName = helpers.ToSnakeCase(fld.Name)
	}
	tblFld.SQLName = flags.Prefix + tblFld.SQLName

	if flags.Sort != "" {
		sort := strings.SplitN(flags.Sort, InKVSeparator, 2)
		tblFld.SortPos, err = strconv.Atoi(sort[0])
		if err != nil {
			return nil, err
		}
		if tblFld.SortPos > 1 {
			tblFld.SortBackward = strings.ToLower(sort[1]) == KeyDesc
		}
	}

	ref := strings.SplitN(flags.Ref, InKVSeparator, 2)
	if len(ref) == 2 {
		tblFld.RefTable, tblFld.RefField = ref[0], ref[1]
	}

	return []TableField{tblFld}, nil
}

func (f *FieldTagFlags) canInsert() bool {
	return f.ForceInsert || !f.ReadOnly && !f.AutoGen
}

func (f *FieldTagFlags) canUpdate() bool {
	return f.ForceUpdate || !f.ReadOnly && !f.IsPK
}

func (f *FieldTagFlags) canSelect() bool {
	return !f.SkipReading
}
