//go:build smoke || crudsgen || functional
// Code generated by crudsgen; DO NOT EDIT.
//nolint:lll
package testmodels

import (
	"context"
	"errors"
	"strings"

	"github.com/mirrorru/cruds"
	"github.com/mirrorru/cruds/defs"
	"github.com/mirrorru/cruds/dialect"
	"github.com/mirrorru/cruds/struct_info"

)

var _ cruds.TypedJoiner[JoinSample] = (*JoinerJoinSample)(nil)

type JoinerJoinSample struct {
	dialect    dialect.SQLDialect
	allFields  struct_info.TableFields
	getOneSQL  string
	getManySQL string
	sortSQL    string

}

func NewJoinerJoinSampleVal(d dialect.SQLDialect) JoinerJoinSample {
	ti0 := &struct_info.TableInfo{
		SQLName: "join_from",
		Fields: struct_info.TableFields{
			{Path: []string{"ID" }, SQLName: "id", IsPK: true, CanSelect: true, SortPos: 1, SortBackward: true},
			{Path: []string{"Name" }, SQLName: "name", CanSelect: true, CanInsert: true, CanUpdate: true},
		},
		FieldNameIdx:  map[string]int{"id": 0, "name": 1 },
		PKIdxList:     []int{0 },
		InsertIdxList: make([]int, 0),
		UpdateIdxList: make([]int, 0),
		SelectIdxList: []int{0, 1 },
		SortIdxList:   []int{0 },
		RefIdxList:    make([]int, 0),
	}

	ti1 := &struct_info.TableInfo{
		SQLName: "join_inner",
		Fields: struct_info.TableFields{
			{Path: []string{"ID" }, SQLName: "id", IsPK: true, CanSelect: true},
			{Path: []string{"RefID" }, SQLName: "ref_id", CanSelect: true, CanInsert: true, CanUpdate: true, SortPos: 1, RefTable: "join_from", RefField: "id"},
			{Path: []string{"InnerVal" }, SQLName: "inner_val", CanSelect: true, CanInsert: true, CanUpdate: true},
		},
		FieldNameIdx:  map[string]int{"id": 0, "ref_id": 1, "inner_val": 2 },
		PKIdxList:     []int{0 },
		InsertIdxList: make([]int, 0),
		UpdateIdxList: make([]int, 0),
		SelectIdxList: []int{0, 1, 2 },
		SortIdxList:   []int{1 },
		RefIdxList:    []int{1 },
	}

	ti2 := &struct_info.TableInfo{
		SQLName: "join_left",
		Fields: struct_info.TableFields{
			{Path: []string{"ID" }, SQLName: "id", IsPK: true, CanSelect: true},
			{Path: []string{"RefID" }, SQLName: "ref_id", CanSelect: true, CanInsert: true, CanUpdate: true, SortPos: 1, SortBackward: true, RefTable: "join_from", RefField: "id"},
			{Path: []string{"LeftVal" }, SQLName: "left_val", CanSelect: true, CanInsert: true, CanUpdate: true},
		},
		FieldNameIdx:  map[string]int{"id": 0, "ref_id": 1, "left_val": 2 },
		PKIdxList:     []int{0 },
		InsertIdxList: make([]int, 0),
		UpdateIdxList: make([]int, 0),
		SelectIdxList: []int{0, 1, 2 },
		SortIdxList:   []int{1 },
		RefIdxList:    []int{1 },
	}

	joinTables := cruds.JoinTables{
		{
			TableInfo:    ti0,
			IsPointer:    false,
			IsFrom:       true,
			IsPK:         false,
			SortPriority: 10,
			JoinModeVal:  cruds.InnerJoin,
			Alias:        "",
			RefAliasMap:  nil,
			Index:        []int{ 0 },
		},
		{
			TableInfo:    ti1,
			IsPointer:    false,
			IsFrom:       false,
			IsPK:         false,
			SortPriority: 20,
			JoinModeVal:  cruds.InnerJoin,
			Alias:        "",
			RefAliasMap:  nil,
			Index:        []int{ 1 },
		},
		{
			TableInfo:    ti2,
			IsPointer:    true,
			IsFrom:       false,
			IsPK:         false,
			SortPriority: 0,
			JoinModeVal:  cruds.LeftJoin,
			Alias:        "LV",
			RefAliasMap:  nil,
			Index:        []int{ 2 },
		},
	}
	jBase, err := cruds.MakeJoinerBase(joinTables, d)
	if err != nil {
		panic(err)
	}
	return JoinerJoinSample{
		dialect:    d,
		allFields:  jBase.AllFields(),
		getOneSQL:  jBase.OneSQL(),
		getManySQL: jBase.ManySQL(),
		sortSQL:    jBase.SortSQL(),
	}
}

func NewJoinerJoinSample(d dialect.SQLDialect) *JoinerJoinSample {
	v := NewJoinerJoinSampleVal(d)
	return &v
}

func (j *JoinerJoinSample) makeRefs(buf *JoinSample) ([]any, func()) {
	var _prLV_ID *int64
	var _prLV_RefID *int64
	var _prLV_LeftVal *string
	return []any{
		&buf.From.ID,
		&buf.From.Name,
		&buf.Inner.ID,
		&buf.Inner.RefID,
		&buf.Inner.InnerVal,
		&_prLV_ID,
		&_prLV_RefID,
		&_prLV_LeftVal,
	}, func() {
		buf.Left = nil
		if _prLV_ID != nil {
			buf.Left = new(JoinLeftRow)
			buf.Left.ID = *_prLV_ID
			buf.Left.RefID = *_prLV_RefID
			buf.Left.LeftVal = *_prLV_LeftVal
		}
	}
}

func (j *JoinerJoinSample) One(ctx context.Context, tx cruds.TxProcessor, keys ...any) (*JoinSample, error) {
	buf := new(JoinSample)
	refs, apply := j.makeRefs(buf)
	err := tx.QueryRowContext(ctx, j.getOneSQL, keys...).Scan(refs...)
	apply()
	return buf, err
}

func (j *JoinerJoinSample) Many(ctx context.Context, tx cruds.TxProcessor, filter *cruds.Filter) (result []*JoinSample, err error) {
	query := j.getManySQL
	var args []any
	if filter != nil {
		if filter.Range != nil {
			var sb strings.Builder
			sb.WriteString(j.getManySQL)
			sb.WriteString(defs.SQLWhere)
			var argIdx int
			where, whereArgs, werr := filter.Range.Build(j.allFields, j.dialect, &argIdx)
			if werr != nil {
				return nil, werr
			}
			sb.WriteString(where)
			query = sb.String()
			args = whereArgs
		}
		if filter.Offset > 0 || filter.Limit > 0 {
			query += j.dialect.OffsetAndLimit(filter.Offset, filter.Limit)
		}
	}
	query += j.sortSQL

	rows, err := tx.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer func() {
		err = errors.Join(err, rows.Close())
	}()

	buf := new(JoinSample)
	refs, apply := j.makeRefs(buf)
	for rows.Next() {
		if err = rows.Scan(refs...); err != nil {
			return nil, err
		}
		apply()
		rec := new(JoinSample)
		*rec = *buf
		result = append(result, rec)
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return result, nil
}
