//go:build smoke || crudsgen || functional
//go:generate crudsgen -src=.:* -dest=test/testmodels -pkg=testmodels
// Code generated by crudsgen v(devel); DO NOT EDIT.

package testmodels

import (
	"context"
	"errors"
	"strings"

	"github.com/mirrorru/cruds"
	"github.com/mirrorru/cruds/defs"
	"github.com/mirrorru/cruds/dialect"
	"github.com/mirrorru/cruds/struct_info"

)

var _ cruds.TypedTable[FuncRow] = (*TableFuncRow)(nil)

type TableFuncRow struct {
	dialect   dialect.SQLDialect
	tableInfo struct_info.TableInfo
	sqlTexts  struct_info.SqlTexts
}

type tableFuncRowInternals struct {
	TableInfo struct_info.TableInfo
	SqlTexts  struct_info.SqlTexts
}

func NewTableFuncRowVal(d dialect.SQLDialect) TableFuncRow {
	tableInfo := struct_info.TableInfo{
		SQLName: "func_row",
		Fields: struct_info.TableFields{
			{Path: []string{"ID" }, SQLName: "id", IsPK: true, CanSelect: true},
			{Path: []string{"Name" }, SQLName: "name", CanSelect: true, CanInsert: true, CanUpdate: true, SortPos: 1},
			{Path: []string{"Value" }, SQLName: "value", CanSelect: true, CanInsert: true, CanUpdate: true},
		},
		FieldNameIdx:  map[string]int{"id": 0, "name": 1, "value": 2 },
		PKIdxList:     []int{0 },
		InsertIdxList: []int{1, 2 },
		UpdateIdxList: []int{1, 2 },
		SelectIdxList: []int{0, 1, 2 },
		SortIdxList:   []int{1 },
		RefIdxList:    []int{ },
	}

	return TableFuncRow{
		dialect:   d,
		tableInfo: tableInfo,
		sqlTexts:  struct_info.SqlBuilderVal.SQLTexts(d, &tableInfo),
	}
}

func NewTableFuncRow(d dialect.SQLDialect) *TableFuncRow {
	return new(NewTableFuncRowVal(d))
}

func (t *TableFuncRow) Internals() tableFuncRowInternals {
	return tableFuncRowInternals{
		TableInfo: t.tableInfo,
		SqlTexts:  t.sqlTexts,
	}
}

func (t *TableFuncRow) scanRefs(buf *FuncRow) []any {
	return []any{&buf.ID, &buf.Name, &buf.Value}
}

func (t *TableFuncRow) insertArgs(row *FuncRow) []any {
	return []any{row.Name, row.Value}
}

func (t *TableFuncRow) updateArgs(row *FuncRow) []any {
	return []any{row.Name, row.Value, row.ID}
}

func (t *TableFuncRow) Ins(ctx context.Context, tx cruds.TxProcessor, row *FuncRow) (*FuncRow, cruds.Result, error) {
	args := t.insertArgs(row)
	if !t.dialect.SupportsReturning() {
		sqlResult, err := tx.ExecContext(ctx, t.sqlTexts.Insert, args)
		return row, sqlResult, err
	}
	buf := new(FuncRow)
	refs := t.scanRefs(buf)
	err := tx.QueryRowContext(ctx, t.sqlTexts.Insert, args...).Scan(refs...)

	return buf, nil, err
}

func (t *TableFuncRow) Upd(ctx context.Context, tx cruds.TxProcessor, row *FuncRow) (*FuncRow, cruds.Result, error) {
	args := t.updateArgs(row)
	if !t.dialect.SupportsReturning() {
		sqlResult, err := tx.ExecContext(ctx, t.sqlTexts.Update, args)
		return row, sqlResult, err
	}
	buf := new(FuncRow)
	refs := t.scanRefs(buf)
	err := tx.QueryRowContext(ctx, t.sqlTexts.Update, args...).Scan(refs...)

	return buf, nil, err
}

func (t *TableFuncRow) One(ctx context.Context, tx cruds.TxProcessor, keys ...any) (*FuncRow, error) {
	buf := new(FuncRow)
	refs := t.scanRefs(buf)
	err := tx.QueryRowContext(ctx, t.sqlTexts.GetOne, keys...).Scan(refs...)

	return buf, err
}

func (t *TableFuncRow) Del(ctx context.Context, tx cruds.TxProcessor, keys ...any) (cruds.Result, error) {
	return tx.ExecContext(ctx, t.sqlTexts.Delete, keys...)
}

func (t *TableFuncRow) Many(ctx context.Context, tx cruds.TxProcessor, filter *cruds.Filter) (result []*FuncRow, err error) {
	var (
		query strings.Builder
		args  []any
		where string
	)
	query.WriteString(t.sqlTexts.ListStart)

	if filter != nil {
		if filter.Range != nil {
			var argIdx int
			where, args, err = filter.Range.Build(t.tableInfo.Fields, t.dialect, &argIdx)
			if err != nil {
				return nil, err
			}
			query.WriteString(defs.SQLWhere)
			query.WriteString(where)
		}
	}
	query.WriteString(t.sqlTexts.SortPart)
	if filter != nil {
		query.WriteString(t.dialect.OffsetAndLimit(filter.Offset, filter.Limit))
	}
	buf := new(FuncRow)
	refs := t.scanRefs(buf)

	rows, err := tx.QueryContext(ctx, query.String(), args...)
	if err != nil {
		return nil, err
	}
	defer func() {
		err = errors.Join(err, rows.Close())
	}()

	for rows.Next() {
		if err = rows.Scan(refs...); err != nil {
			return nil, err
		}
		rec := new(FuncRow)
		*rec = *buf
		result = append(result, rec)
	}

	if err = rows.Err(); err != nil {
		return nil, err
	}

	return result, nil
}
