//go:build smoke || crudsgen || functional
// Code generated by crudsgen; DO NOT EDIT.

package testmodels

import (
	"context"
	"errors"
	"strings"

	"github.com/mirrorru/cruds"
	"github.com/mirrorru/cruds/defs"
	"github.com/mirrorru/cruds/dialect"
	"github.com/mirrorru/cruds/struct_info"

)

var _ cruds.TypedTable[IdNameAgeRowFilled] = (*TableIdNameAgeRowFilled)(nil)

type TableIdNameAgeRowFilled struct {
	dialect   dialect.SQLDialect
	tableInfo struct_info.TableInfo
	sqlTexts  struct_info.SqlTexts
}

type tableIdNameAgeRowFilledInternals struct {
	TableInfo struct_info.TableInfo
	SqlTexts  struct_info.SqlTexts
}

func NewTableIdNameAgeRowFilledVal(d dialect.SQLDialect) TableIdNameAgeRowFilled {
	tableInfo := struct_info.TableInfo{
		SQLName: "id_name_age_filled",
		Fields: struct_info.TableFields{
			{Path: []string{"ID" }, SQLName: "id", IsPK: true, CanSelect: true, CanInsert: true},
			{Path: []string{"Name" }, SQLName: "name", CanSelect: true, CanInsert: true, CanUpdate: true, SortPos: 1},
			{Path: []string{"Age" }, SQLName: "age", CanSelect: true, CanInsert: true, CanUpdate: true},
		},
		FieldNameIdx:  map[string]int{"id": 0, "name": 1, "age": 2 },
		PKIdxList:     []int{0 },
		InsertIdxList: []int{0, 1, 2 },
		UpdateIdxList: []int{1, 2 },
		SelectIdxList: []int{0, 1, 2 },
		SortIdxList:   []int{1 },
		RefIdxList:    []int{ },
	}

	return TableIdNameAgeRowFilled{
		dialect:   d,
		tableInfo: tableInfo,
		sqlTexts:  struct_info.SqlBuilderVal.SQLTexts(d, &tableInfo),
	}
}

func NewTableIdNameAgeRowFilled(d dialect.SQLDialect) *TableIdNameAgeRowFilled {
	return new(NewTableIdNameAgeRowFilledVal(d))
}

func (t *TableIdNameAgeRowFilled) Internals() tableIdNameAgeRowFilledInternals {
	return tableIdNameAgeRowFilledInternals{
		TableInfo: t.tableInfo,
		SqlTexts:  t.sqlTexts,
	}
}

func (t *TableIdNameAgeRowFilled) scanRefs(buf *IdNameAgeRowFilled) []any {
	return []any{&buf.ID, &buf.Name, &buf.Age}
}

func (t *TableIdNameAgeRowFilled) insertArgs(row *IdNameAgeRowFilled) []any {
	return []any{row.ID, row.Name, row.Age}
}

func (t *TableIdNameAgeRowFilled) updateArgs(row *IdNameAgeRowFilled) []any {
	return []any{row.Name, row.Age, row.ID}
}

func (t *TableIdNameAgeRowFilled) Ins(ctx context.Context, tx cruds.TxProcessor, row *IdNameAgeRowFilled) (*IdNameAgeRowFilled, cruds.Result, error) {
	args := t.insertArgs(row)
	if !t.dialect.SupportsReturning() {
		sqlResult, err := tx.ExecContext(ctx, t.sqlTexts.Insert, args)
		return row, sqlResult, err
	}
	buf := new(IdNameAgeRowFilled)
	refs := t.scanRefs(buf)
	err := tx.QueryRowContext(ctx, t.sqlTexts.Insert, args...).Scan(refs...)

	return buf, nil, err
}

func (t *TableIdNameAgeRowFilled) Upd(ctx context.Context, tx cruds.TxProcessor, row *IdNameAgeRowFilled) (*IdNameAgeRowFilled, cruds.Result, error) {
	args := t.updateArgs(row)
	if !t.dialect.SupportsReturning() {
		sqlResult, err := tx.ExecContext(ctx, t.sqlTexts.Update, args)
		return row, sqlResult, err
	}
	buf := new(IdNameAgeRowFilled)
	refs := t.scanRefs(buf)
	err := tx.QueryRowContext(ctx, t.sqlTexts.Update, args...).Scan(refs...)

	return buf, nil, err
}

func (t *TableIdNameAgeRowFilled) One(ctx context.Context, tx cruds.TxProcessor, keys ...any) (*IdNameAgeRowFilled, error) {
	buf := new(IdNameAgeRowFilled)
	refs := t.scanRefs(buf)
	err := tx.QueryRowContext(ctx, t.sqlTexts.GetOne, keys...).Scan(refs...)

	return buf, err
}

func (t *TableIdNameAgeRowFilled) Del(ctx context.Context, tx cruds.TxProcessor, keys ...any) (cruds.Result, error) {
	return tx.ExecContext(ctx, t.sqlTexts.Delete, keys...)
}

func (t *TableIdNameAgeRowFilled) Many(ctx context.Context, tx cruds.TxProcessor, filter *cruds.Filter) (result []*IdNameAgeRowFilled, err error) {
	var (
		query strings.Builder
		args  []any
		where string
	)
	query.WriteString(t.sqlTexts.ListStart)

	if filter != nil {
		if filter.Range != nil {
			var argIdx int
			where, args, err = filter.Range.Build(t.tableInfo.Fields, t.dialect, &argIdx)
			if err != nil {
				return nil, err
			}
			query.WriteString(defs.SQLWhere)
			query.WriteString(where)
		}
	}
	query.WriteString(t.sqlTexts.SortPart)
	if filter != nil {
		query.WriteString(t.dialect.OffsetAndLimit(filter.Offset, filter.Limit))
	}
	buf := new(IdNameAgeRowFilled)
	refs := t.scanRefs(buf)

	rows, err := tx.QueryContext(ctx, query.String(), args...)
	if err != nil {
		return nil, err
	}
	defer func() {
		err = errors.Join(err, rows.Close())
	}()

	for rows.Next() {
		if err = rows.Scan(refs...); err != nil {
			return nil, err
		}
		rec := new(IdNameAgeRowFilled)
		*rec = *buf
		result = append(result, rec)
	}

	if err = rows.Err(); err != nil {
		return nil, err
	}

	return result, nil
}
